name: build-cpp

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create CMake build files
        shell: pwsh
        working-directory: ${{github.workspace}}/src/cpp
        run: |
          cmake -B build -S . "-DCMAKE_TOOLCHAIN_FILE=$Env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Compile the project
        working-directory: ${{github.workspace}}/src/cpp
        run: |
          cmake --build build --config Debug -j8

      - name: Run the tests
        working-directory: ${{github.workspace}}/src/cpp/build
        run: |
          ctest
